-- Sistem kaynak izleme: CPU/RAM/disk esik uyarilari.
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "sysMonitorEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "cpuAlertPct" INTEGER NOT NULL DEFAULT 90;
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "memAlertPct" INTEGER NOT NULL DEFAULT 90;
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "diskAlertPct" INTEGER NOT NULL DEFAULT 90;
