ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "serverUrls" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "primaryUrlIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "settings" ADD COLUMN IF NOT EXISTS "urlHealthCheck" BOOLEAN NOT NULL DEFAULT true;
